# Define the TypeScript Language Server once
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "9c84af007b0f144954adb26b3f336495cbb320a7" }

# JavaScript Configuration (using the same TypeScript Language Server)
[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "js|javascript"
file-types = ["js"]
roots = ["package.json", "node_modules", ".git"]
auto-format = true
shebangs = ["node"]
block-comment-tokens = [
  { start = "/*", end = "*/" }
]
language-servers = ["typescript-language-server"]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev = "f933a9a96a62f8dd5cd55544ae8d81f92a8df99b" }



# HTML Configuration
[[language]]
name = "html"
scope = "text.html.basic"
file-types = ["html", "htm"]
language-servers = ["vscode-html-language-server"]

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "fc20c54bdf37e34f091d81d173178c9540a02cf7" }



[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ".git"]
language-servers = ["jdtls"]

[language-server.jdtls]
command = "/home/suraj/.local/share/java/jdtls/bin/jdtls"
args = ["-configuration", "/home/suraj/.local/share/java/jdtls/config_linux", "-data", "/home/suraj/.cache/jdtls/workspace"]

[[grammar]]
name = "java"
source = { git = "https://github.com/tree-sitter/tree-sitter-java", rev = "9b707e50c63c054e390ff16a36c7d17b4ed9f1b6" }











